service: fetch-tweet-and-store

frameworkVersion: ">=1.1.0"

custom:
  bucket: we-save-you-tweet

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:iam::547890:user/gokulsports77:${self:custom.bucket}/*"

functions:
  save:
    handler: handler.save
    environment:
      BUCKET: ${self:custom.bucket}
